#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-2 -d 0

bspc config border_width         2
bspc config window_gap           6 
#bspc config top_pading           20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a Brave-browser desktop='^3' follow=off
bspc rule -a Thunderbird desktop='^4'
bspc rule -a Virt-manager desktop='^5'
bspc rule -a Steam desktop='^6'
bspc rule -a Transmission-gtk desktop='^7'
bspc rule -a Signal desktop='^8' follow=off

bspc rule -a MEGAsync state=floating
bspc rule -a flameshot state=floating
bspc rule -a Zathura state=tiled
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Exec stuff

# Fix Mouse cursor on startup 
xsetroot -cursor_name left_ptr

# Set mouse acceleration, xinput list (list device), xinput --list-props <device id>
xinput --set-prop 8 'libinput Accel Speed' -0.9

$HOME/.config/polybar/launch.sh

#cbatticon &
#nitrogen --restore &
feh --bg-fill  ~/.wallpaper &
if [[ ! $( pgrep dunst ) ]]; then $( dunst ); fi &
if [[ ! $( pgrep picom ) ]]; then $( picom ); fi &
if [[ ! $( pgrep nm-applet ) ]]; then $( nm-applet ); fi &
if [[ ! $( pgrep megasync ) ]]; then $( megasync ); fi &

/usr/bin/find ~ -type f

#alttab -d 2 -w 1 -fg '#d0d0d0' -bg "#4b4b4b" -frame "#ffaf00" -t 128x125 -i 127x64 -font "xft:Fira Sans Book-9" &
