#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5 6 7 9
bspc monitor HDMI-2 -d 8

bspc config border_width         2
bspc config window_gap           6 
#bspc config top_pading           20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^3' 
bspc rule -a Thunderbird desktop='^4'
bspc rule -a Virt-manager desktop='^5'
bspc rule -a Steam desktop='^6'
bspc rule -a Transmission-gtk desktop='^7'

bspc rule -a MEGAsync state=floating
bspc rule -a flameshot state=floating
bspc rule -a Zathura state=tiled
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# exec stuff

$HOME/.config/polybar/launch.sh
picom  &
#cbatticon &
#nitrogen --restore &
feh --recursive --bg-fill --randomize ~/Pictures/Wall
nm-applet &
megasync &
xsetroot -cursor_name left_ptr &
alttab -d 2 -w 1 -fg '#d0d0d0' -bg "#4b4b4b" -frame "#ffaf00" -t 128x125 -i 127x64 -font "xft:Fira Sans Book-9" &

