#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr | grep -i 'DP-0 connected') ]]
then
    bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9
    bspc monitor HDMI-2 -d 0
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

bspc config border_width         2
bspc config window_gap           6 
#bspc config top_pading           20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^1' follow=off
bspc rule -a thunderbird desktop='^2'
bspc rule -a Tmux desktop='^3' follow=on
bspc rule -a Org.gnome.Nautilus desktop='^4' follow=on
#bspc rule -a Thunar desktop='^4' follow=on
bspc rule -a Signal desktop='^5' follow=off
bspc rule -a Virt-manager desktop='^6'
bspc rule -a Steam desktop='^7'
bspc rule -a Transmission-gtk desktop='^8'

bspc rule -a MEGAsync state=floating
bspc rule -a flameshot state=floating
bspc rule -a Zathura state=tiled
#bspc rule -a FZF_Search state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Exec stuff

rm $HOME/.config/polybar && ln -s $HOME/.dotfiles/.config/polybar.bspwm/ $HOME/.config/polybar
$HOME/.config/polybar/launch.sh

# Fix Mouse cursor on startup 
xsetroot -cursor_name left_ptr

# Set mouse acceleration, xinput list (list device), xinput --list-props <device id>
xinput --set-prop 8 'libinput Accel Speed' -0.9
xinput --set-prop 8 'libinput High Resolution Wheel Scroll Enabled' 0

#pgrep -x cbatticon > /dev/null || cbatticon &
#pgrep -x nitrogen > /dev/null || --restore &
pgrep -x feh > /dev/null || feh --bg-fill  ~/.wallpaper &
pgrep -x dunst > /dev/null || dunst &
pgrep -x picom > /dev/null || picom &
#pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x megasync > /dev/null || megasync &

/usr/bin/find ~ -type f

#alttab -d 2 -w 1 -fg '#d0d0d0' -bg "#4b4b4b" -frame "#ffaf00" -t 128x125 -i 127x64 -font "xft:Fira Sans Book-9" &
