#!/usr/bin/env bash

charge=$(acpi -b | grep -oP "\d+%" | tr -d "%")
battstat=$(acpi -b | awk '{print $3}')

if [[ $battstat == Dis* ]];
then
  if [[ $charge -lt 10 ]];
  then
    #color=#FF0000
    notify-send ":::::BATTERY LOW:::::" "$(acpi -b)"
    echo " $charge%"
  elif [[ $charge -lt 30 ]];
  then
    #color=#FFAE00
    echo " $charge%"
  elif [[ $charge -lt 60 ]];
  then
    #color=#FFF600
    echo " $charge%"
  elif [[ $charge -lt 85 ]];
  then
    #color=#A8FF00
    echo " $charge%"
  else  
    echo " $charge%"
  fi
else
  echo "" 
fi

if [[ "$BLOCK_BUTTON" -eq 1 ]]; then 
    notify-send -t 10000 "BATTERY" "$(acpi -a;acpi -i)"
fi
